import { RankedAd, AdFormData } from "./types";

const initialAds: RankedAd[] = [
  {
    id: "1",
    name: "فروشگاه آنلاین دیجی‌کالا",
    text: "بزرگترین فروشگاه آنلاین ایران با میلیون‌ها محصول متنوع. تخفیف‌های ویژه هر روز!",
    category: "shopping",
    telegramLink: "https://t.me/digikala",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=400&h=300&fit=crop",
    members: 250000,
    tags: ["popular", "verified", "discount"],
    cities: ["tehran", "mashhad", "isfahan"],
    ageGroups: ["youth", "adults"],
    relevanceScore: 0.95,
  },
  {
    id: "2",
    name: "استخدام برنامه‌نویس",
    text: "جذب نیرو در شرکت‌های معتبر IT. فرصت‌های شغلی برای توسعه‌دهندگان وب و موبایل.",
    category: "jobs",
    telegramLink: "https://t.me/devjobs_ir",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=400&h=300&fit=crop",
    members: 85000,
    tags: ["new", "active", "trusted"],
    cities: ["tehran", "karaj"],
    ageGroups: ["youth", "adults"],
    relevanceScore: 0.88,
  },
  {
    id: "3",
    name: "آموزش زبان انگلیسی",
    text: "یادگیری زبان انگلیسی با بهترین اساتید. کلاس‌های آنلاین و حضوری.",
    category: "education",
    telegramLink: "https://t.me/english_learn_ir",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400&h=300&fit=crop",
    members: 120000,
    tags: ["verified", "popular", "premium"],
    cities: ["tehran", "mashhad", "shiraz"],
    ageGroups: ["youth", "adults", "middle"],
    relevanceScore: 0.92,
  },
  {
    id: "4",
    name: "گیمرهای ایران",
    text: "بزرگترین کامیونیتی گیمرهای ایرانی. اخبار بازی، تورنومنت‌ها و گفتگو.",
    category: "entertainment",
    telegramLink: "https://t.me/gamers_iran",
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    members: 180000,
    tags: ["popular", "active", "free"],
    cities: ["tehran", "isfahan", "tabriz"],
    ageGroups: ["youth"],
    relevanceScore: 0.85,
  },
  {
    id: "5",
    name: "سلامت و تندرستی",
    text: "مشاوره پزشکی آنلاین، نکات سلامتی و تغذیه سالم از متخصصین.",
    category: "health",
    telegramLink: "https://t.me/health_tips_ir",
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=400&h=300&fit=crop",
    members: 95000,
    tags: ["verified", "trusted", "premium"],
    cities: ["tehran", "mashhad", "qom"],
    ageGroups: ["adults", "middle", "senior"],
    relevanceScore: 0.82,
  },
  {
    id: "6",
    name: "اخبار روز ایران",
    text: "آخرین اخبار سیاسی، اقتصادی و اجتماعی ایران و جهان. به‌روزرسانی ۲۴ ساعته.",
    category: "news",
    telegramLink: "https://t.me/news_iran_daily",
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=400&h=300&fit=crop",
    members: 320000,
    tags: ["popular", "active", "verified"],
    cities: ["tehran"],
    ageGroups: ["all"],
    relevanceScore: 0.98,
  },
  {
    id: "7",
    name: "موسیقی پاپ ایران",
    text: "جدیدترین آهنگ‌های پاپ فارسی، کنسرت‌ها و اخبار هنرمندان محبوب.",
    category: "music",
    telegramLink: "https://t.me/pop_music_ir",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop",
    members: 210000,
    tags: ["popular", "free", "active"],
    cities: ["tehran", "shiraz", "isfahan"],
    ageGroups: ["youth", "adults"],
    relevanceScore: 0.89,
  },
  {
    id: "8",
    name: "رستوران‌های تهران",
    text: "معرفی بهترین رستوران‌ها، کافه‌ها و غذاخوری‌های تهران با تخفیف ویژه.",
    category: "food",
    telegramLink: "https://t.me/tehran_restaurants",
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400&h=300&fit=crop",
    members: 75000,
    tags: ["discount", "new", "trusted"],
    cities: ["tehran"],
    ageGroups: ["youth", "adults", "middle"],
    relevanceScore: 0.78,
  },
  {
    id: "9",
    name: "خرید و فروش خودرو",
    text: "بازار خودرو ایران. خرید، فروش و معاوضه انواع خودرو صفر و کارکرده.",
    category: "automotive",
    telegramLink: "https://t.me/car_market_ir",
    createdAt: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=400&h=300&fit=crop",
    members: 145000,
    tags: ["popular", "verified", "active"],
    cities: ["tehran", "karaj", "tabriz", "mashhad"],
    ageGroups: ["adults", "middle"],
    relevanceScore: 0.86,
  },
  {
    id: "10",
    name: "املاک و مستغلات",
    text: "خرید، فروش و اجاره آپارتمان، ویلا و زمین در سراسر ایران.",
    category: "realestate",
    telegramLink: "https://t.me/realestate_ir",
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&h=300&fit=crop",
    members: 190000,
    tags: ["verified", "trusted", "premium"],
    cities: ["tehran", "karaj", "isfahan", "shiraz"],
    ageGroups: ["adults", "middle", "senior"],
    relevanceScore: 0.91,
  },
  {
    id: "11",
    name: "تکنولوژی و گجت",
    text: "بررسی جدیدترین گوشی‌ها، لپ‌تاپ‌ها و گجت‌های تکنولوژی روز دنیا.",
    category: "tech",
    telegramLink: "https://t.me/tech_gadgets_ir",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=400&h=300&fit=crop",
    members: 165000,
    tags: ["new", "popular", "verified"],
    cities: ["tehran", "mashhad"],
    ageGroups: ["youth", "adults"],
    relevanceScore: 0.93,
  },
  {
    id: "12",
    name: "همشهری تهران",
    text: "گروه اجتماعی شهروندان تهران. رویدادها، مشکلات شهری و گفتگوی همشهری‌ها.",
    category: "social",
    telegramLink: "https://t.me/hamshahri_tehran",
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=400&h=300&fit=crop",
    members: 55000,
    tags: ["active", "free", "trusted"],
    cities: ["tehran"],
    ageGroups: ["all"],
    relevanceScore: 0.75,
  },
];

let ads: RankedAd[] = [...initialAds];

export async function getAds(): Promise<RankedAd[]> {
  await new Promise((resolve) => setTimeout(resolve, 500));
  return [...ads];
}

export async function addAd(data: AdFormData): Promise<RankedAd> {
  await new Promise((resolve) => setTimeout(resolve, 300));
  
  const newAd: RankedAd = {
    ...data,
    id: Date.now().toString(),
    createdAt: new Date().toISOString(),
    relevanceScore: Math.random() * 0.3 + 0.7,
  };
  
  ads = [newAd, ...ads];
  return newAd;
}
