import {
  ShoppingBag,
  Briefcase,
  GraduationCap,
  Gamepad2,
  Heart,
  Newspaper,
  Music,
  Utensils,
  Car,
  Home,
  Laptop,
  Users,
  type LucideIcon,
} from "lucide-react";

export interface Category {
  value: string;
  label: string;
  icon: LucideIcon;
}

export const CATEGORIES: Category[] = [
  { value: "shopping", label: "خرید و فروش", icon: ShoppingBag },
  { value: "jobs", label: "کار و استخدام", icon: Briefcase },
  { value: "education", label: "آموزش", icon: GraduationCap },
  { value: "entertainment", label: "سرگرمی", icon: Gamepad2 },
  { value: "health", label: "سلامت", icon: Heart },
  { value: "news", label: "اخبار", icon: Newspaper },
  { value: "music", label: "موسیقی", icon: Music },
  { value: "food", label: "غذا و رستوران", icon: Utensils },
  { value: "automotive", label: "خودرو", icon: Car },
  { value: "realestate", label: "املاک", icon: Home },
  { value: "tech", label: "تکنولوژی", icon: Laptop },
  { value: "social", label: "اجتماعی", icon: Users },
];

export const CITIES = [
  { value: "tehran", label: "تهران" },
  { value: "mashhad", label: "مشهد" },
  { value: "isfahan", label: "اصفهان" },
  { value: "shiraz", label: "شیراز" },
  { value: "tabriz", label: "تبریز" },
  { value: "karaj", label: "کرج" },
  { value: "ahvaz", label: "اهواز" },
  { value: "qom", label: "قم" },
  { value: "kermanshah", label: "کرمانشاه" },
  { value: "rasht", label: "رشت" },
  { value: "yazd", label: "یزد" },
  { value: "urmia", label: "ارومیه" },
  { value: "zahedan", label: "زاهدان" },
  { value: "hamadan", label: "همدان" },
  { value: "arak", label: "اراک" },
  { value: "ardabil", label: "اردبیل" },
  { value: "sanandaj", label: "سنندج" },
  { value: "gorgan", label: "گرگان" },
  { value: "sari", label: "ساری" },
  { value: "bandarabbas", label: "بندرعباس" },
  { value: "birjand", label: "بیرجند" },
  { value: "bojnurd", label: "بجنورد" },
  { value: "bushehr", label: "بوشهر" },
  { value: "ilam", label: "ایلام" },
  { value: "khorramabad", label: "خرم‌آباد" },
  { value: "yasuj", label: "یاسوج" },
  { value: "zanjan", label: "زنجان" },
  { value: "semnan", label: "سمنان" },
  { value: "shahroud", label: "شاهرود" },
  { value: "shahr-e-kord", label: "شهرکرد" },
  { value: "kerman", label: "کرمان" },
  { value: "qazvin", label: "قزوین" },
  { value: "khoy", label: "خوی" },
  { value: "kashan", label: "کاشان" },
  { value: "dezful", label: "دزفول" },
  { value: "sabzevar", label: "سبزوار" },
  { value: "neyshabur", label: "نیشابور" },
  { value: "babol", label: "بابل" },
  { value: "amol", label: "آمل" },
  { value: "qaemshahr", label: "قائم‌شهر" },
  { value: "islamshahr", label: "اسلامشهر" },
  { value: "malayer", label: "ملایر" },
  { value: "varamin", label: "ورامین" },
  { value: "abadan", label: "آبادان" },
  { value: "pakdasht", label: "پاکدشت" },
  { value: "saveh", label: "ساوه" },
  { value: "khoramshahr", label: "خرمشهر" },
  { value: "bukan", label: "بوکان" },
  { value: "mahabad", label: "مهاباد" },
  { value: "miandoab", label: "میاندوآب" },
  { value: "maragheh", label: "مراغه" },
  { value: "marand", label: "مرند" },
  { value: "bonab", label: "بناب" },
  { value: "ajabshir", label: "عجب‌شیر" },
  { value: "sarab", label: "سراب" },
  { value: "ahar", label: "اهر" },
  { value: "shabestar", label: "شبستر" },
  { value: "baneh", label: "بانه" },
  { value: "saqqez", label: "سقز" },
  { value: "marivan", label: "مریوان" },
  { value: "qorveh", label: "قروه" },
  { value: "bijar", label: "بیجار" },
  { value: "kamyaran", label: "کامیاران" },
  { value: "eslamabad-e-gharb", label: "اسلام‌آباد غرب" },
  { value: "kangavar", label: "کنگاور" },
  { value: "sonqor", label: "سنقر" },
  { value: "paveh", label: "پاوه" },
  { value: "harsin", label: "هرسین" },
  { value: "javanrud", label: "جوانرود" },
  { value: "ravansar", label: "روانسر" },
  { value: "sahneh", label: "صحنه" },
  { value: "tuyserkan", label: "تویسرکان" },
  { value: "nahavand", label: "نهاوند" },
  { value: "asadabad", label: "اسدآباد" },
  { value: "razan", label: "رزن" },
  { value: "bahar", label: "بهار" },
  { value: "kaboudrahang", label: "کبودرآهنگ" },
  { value: "famenin", label: "فامنین" },
  { value: "borujerd", label: "بروجرد" },
  { value: "dorud", label: "دورود" },
  { value: "aligudarz", label: "الیگودرز" },
  { value: "azna", label: "ازنا" },
  { value: "kuhdasht", label: "کوهدشت" },
  { value: "nurabad", label: "نورآباد" },
  { value: "rumeshkan", label: "رومشکان" },
  { value: "pol-e-dokhtar", label: "پلدختر" },
  { value: "mehran", label: "مهران" },
  { value: "dehloran", label: "دهلران" },
  { value: "ivan", label: "ایوان" },
  { value: "abdanan", label: "آبدانان" },
  { value: "darrehshahr", label: "دره‌شهر" },
  { value: "gachsaran", label: "گچساران" },
  { value: "dehdasht", label: "دهدشت" },
  { value: "dogonbadan", label: "دوگنبدان" },
  { value: "nurabad-mamasani", label: "نورآباد ممسنی" },
  { value: "firuzabad", label: "فیروزآباد" },
  { value: "jahrom", label: "جهرم" },
  { value: "fasa", label: "فسا" },
  { value: "darab", label: "داراب" },
  { value: "larestan", label: "لارستان" },
  { value: "lamerd", label: "لامرد" },
  { value: "mohr", label: "مهر" },
  { value: "kazerun", label: "کازرون" },
  { value: "neyriz", label: "نی‌ریز" },
  { value: "abadeh", label: "آباده" },
  { value: "eqlid", label: "اقلید" },
  { value: "sepidan", label: "سپیدان" },
  { value: "marvdasht", label: "مرودشت" },
  { value: "bam", label: "بم" },
  { value: "jiroft", label: "جیرفت" },
  { value: "sirjan", label: "سیرجان" },
  { value: "rafsanjan", label: "رفسنجان" },
  { value: "zarand", label: "زرند" },
  { value: "baft", label: "بافت" },
  { value: "bardsir", label: "بردسیر" },
  { value: "shahr-e-babak", label: "شهربابک" },
  { value: "chabahar", label: "چابهار" },
  { value: "iranshahr", label: "ایرانشهر" },
  { value: "saravan", label: "سراوان" },
  { value: "khash", label: "خاش" },
  { value: "nikshahr", label: "نیکشهر" },
  { value: "konarak", label: "کنارک" },
  { value: "zahak", label: "زاهک" },
  { value: "torbat-e-heydarieh", label: "تربت حیدریه" },
  { value: "torbat-e-jam", label: "تربت جام" },
  { value: "taybad", label: "تایباد" },
  { value: "gonabad", label: "گناباد" },
  { value: "kashmar", label: "کاشمر" },
  { value: "fariman", label: "فریمان" },
  { value: "sarakhs", label: "سرخس" },
  { value: "quchan", label: "قوچان" },
  { value: "shirvan", label: "شیروان" },
  { value: "esfarayen", label: "اسفراین" },
  { value: "jajarm", label: "جاجرم" },
  { value: "ferdows", label: "فردوس" },
  { value: "qaen", label: "قاین" },
  { value: "nehbandan", label: "نهبندان" },
  { value: "tabas", label: "طبس" },
  { value: "sarbisheh", label: "سربیشه" },
  { value: "aliabad-e-katul", label: "علی‌آباد کتول" },
  { value: "gonbad-e-kavus", label: "گنبد کاووس" },
  { value: "bandar-e-gaz", label: "بندر گز" },
  { value: "bandar-e-torkaman", label: "بندر ترکمن" },
  { value: "kordkuy", label: "کردکوی" },
  { value: "azadshahr", label: "آزادشهر" },
  { value: "minudasht", label: "مینودشت" },
  { value: "ramsar", label: "رامسر" },
  { value: "chalus", label: "چالوس" },
  { value: "noshahr", label: "نوشهر" },
  { value: "tonekabon", label: "تنکابن" },
  { value: "lahijan", label: "لاهیجان" },
  { value: "langarud", label: "لنگرود" },
  { value: "rudsar", label: "رودسر" },
  { value: "astaneh-ye-ashrafiyeh", label: "آستانه اشرفیه" },
  { value: "fuman", label: "فومن" },
  { value: "sowmeh-sara", label: "صومعه‌سرا" },
  { value: "rudbar", label: "رودبار" },
  { value: "shaft", label: "شفت" },
  { value: "rezvanshahr", label: "رضوانشهر" },
  { value: "talesh", label: "تالش" },
  { value: "astara", label: "آستارا" },
  { value: "bandar-e-anzali", label: "بندر انزلی" },
  { value: "masal", label: "ماسال" },
  { value: "meshkin-shahr", label: "مشگین‌شهر" },
  { value: "parsabad", label: "پارس‌آباد" },
  { value: "khalkhal", label: "خلخال" },
  { value: "namin", label: "نمین" },
  { value: "nir", label: "نیر" },
  { value: "bilesavar", label: "بیله‌سوار" },
  { value: "germi", label: "گرمی" },
  { value: "kowsar", label: "کوثر" },
  { value: "takab", label: "تکاب" },
  { value: "naghadeh", label: "نقده" },
  { value: "salmas", label: "سلماس" },
  { value: "shahindej", label: "شاهین‌دژ" },
  { value: "piranshahr", label: "پیرانشهر" },
  { value: "sardasht", label: "سردشت" },
  { value: "oshnavieh", label: "اشنویه" },
  { value: "chaldoran", label: "چالدران" },
  { value: "showt", label: "شوط" },
  { value: "poldasht", label: "پلدشت" },
  { value: "abhar", label: "ابهر" },
  { value: "khodabandeh", label: "خدابنده" },
  { value: "khorramdarreh", label: "خرمدره" },
  { value: "mahneshan", label: "ماهنشان" },
  { value: "tarom", label: "طارم" },
  { value: "ijrud", label: "ایجرود" },
  { value: "damghan", label: "دامغان" },
  { value: "garmsar", label: "گرمسار" },
  { value: "mehdishahr", label: "مهدیشهر" },
  { value: "meyami", label: "میامی" },
  { value: "sorkheh", label: "سرخه" },
  { value: "takestan", label: "تاکستان" },
  { value: "alborz", label: "البرز" },
  { value: "buin-zahra", label: "بوئین‌زهرا" },
  { value: "avaj", label: "آوج" },
  { value: "mobarakeh", label: "مبارکه" },
  { value: "shahinshahr", label: "شاهین‌شهر" },
  { value: "najafabad", label: "نجف‌آباد" },
  { value: "khomeinishahr", label: "خمینی‌شهر" },
  { value: "falavarjan", label: "فلاورجان" },
  { value: "lenjan", label: "لنجان" },
  { value: "tiran", label: "تیران" },
  { value: "chadegan", label: "چادگان" },
  { value: "fereydan", label: "فریدن" },
  { value: "ardestan", label: "اردستان" },
  { value: "nain", label: "نائین" },
  { value: "khansar", label: "خوانسار" },
  { value: "golpayegan", label: "گلپایگان" },
  { value: "natanz", label: "نطنز" },
  { value: "khomein", label: "خمین" },
  { value: "delijan", label: "دلیجان" },
  { value: "ashtian", label: "آشتیان" },
  { value: "tafresh", label: "تفرش" },
  { value: "shazand", label: "شازند" },
  { value: "mahalat", label: "محلات" },
  { value: "abarqu", label: "ابرکوه" },
  { value: "meybod", label: "میبد" },
  { value: "taft", label: "تفت" },
  { value: "bafq", label: "بافق" },
  { value: "mehriz", label: "مهریز" },
  { value: "khatam", label: "خاتم" },
  { value: "ardakan", label: "اردکان" },
  { value: "behshahr", label: "بهشهر" },
  { value: "neka", label: "نکا" },
  { value: "juybar", label: "جویبار" },
  { value: "mahmudabad", label: "محمودآباد" },
  { value: "fereydunkenar", label: "فریدونکنار" },
  { value: "babolsar", label: "بابلسر" },
  { value: "nur", label: "نور" },
  { value: "ghaemshahr", label: "قائمشهر" },
  { value: "savadkuh", label: "سوادکوه" },
  { value: "darab-2", label: "دراب" },
  { value: "firuzkooh", label: "فیروزکوه" },
  { value: "damavand", label: "دماوند" },
  { value: "pardis", label: "پردیس" },
  { value: "rey", label: "ری" },
  { value: "robat-karim", label: "رباط‌کریم" },
  { value: "shahriar", label: "شهریار" },
  { value: "mallard", label: "ملارد" },
  { value: "eslamshahr", label: "اسلام‌شهر" },
  { value: "baharestan", label: "بهارستان" },
  { value: "qods", label: "قدس" },
  { value: "pishva", label: "پیشوا" },
  { value: "fardis", label: "فردیس" },
  { value: "nazarabad", label: "نظرآباد" },
  { value: "hashtgerd", label: "هشتگرد" },
  { value: "eshtehard", label: "اشتهارد" },
  { value: "taleghan", label: "طالقان" },
  { value: "bostan-abad", label: "بستان‌آباد" },
  { value: "osku", label: "اسکو" },
  { value: "varzaqan", label: "ورزقان" },
  { value: "mianeh", label: "میانه" },
  { value: "hashtrood", label: "هشترود" },
  { value: "charoymaq", label: "چاراویماق" },
  { value: "heris", label: "هریس" },
  { value: "jolfa", label: "جلفا" },
  { value: "behbahan", label: "بهبهان" },
  { value: "andimeshk", label: "اندیمشک" },
  { value: "shushtar", label: "شوشتر" },
  { value: "shush", label: "شوش" },
  { value: "izeh", label: "ایذه" },
  { value: "masjed-soleyman", label: "مسجدسلیمان" },
  { value: "omidiyeh", label: "امیدیه" },
  { value: "ramhormoz", label: "رامهرمز" },
  { value: "mahshahr", label: "ماهشهر" },
  { value: "shadegan", label: "شادگان" },
  { value: "susangerd", label: "سوسنگرد" },
  { value: "hoveyzeh", label: "هویزه" },
  { value: "dashti", label: "دشتی" },
  { value: "dashtestan", label: "دشتستان" },
  { value: "tangestan", label: "تنگستان" },
  { value: "genaveh", label: "گناوه" },
  { value: "kangan", label: "کنگان" },
  { value: "dayyer", label: "دیّر" },
  { value: "jam", label: "جم" },
  { value: "asaluyeh", label: "عسلویه" },
  { value: "qeshm", label: "قشم" },
  { value: "kish", label: "کیش" },
  { value: "hormuz", label: "هرمز" },
  { value: "minab", label: "میناب" },
  { value: "rudan", label: "رودان" },
  { value: "jask", label: "جاسک" },
  { value: "bashagard", label: "بشاگرد" },
  { value: "sirik", label: "سیریک" },
  { value: "hajjiabad", label: "حاجی‌آباد" },
  { value: "parsian", label: "پارسیان" },
  { value: "bandar-e-lengeh", label: "بندر لنگه" },
  { value: "bastak", label: "بستک" },
];

export const TAGS = [
  { value: "free", label: "رایگان" },
  { value: "discount", label: "تخفیف" },
  { value: "new", label: "جدید" },
  { value: "verified", label: "تأیید شده" },
  { value: "popular", label: "محبوب" },
  { value: "premium", label: "ویژه" },
  { value: "trusted", label: "معتبر" },
  { value: "active", label: "فعال" },
];

export const AGE_GROUPS = [
  { value: "youth", label: "جوانان (۱۸-۲۵)" },
  { value: "adults", label: "بزرگسالان (۲۵-۴۰)" },
  { value: "middle", label: "میانسال (۴۰-۶۰)" },
  { value: "senior", label: "سالمندان (۶۰+)" },
  { value: "all", label: "همه سنین" },
];
